apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: postman-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: postman-test 
  name: postman-test
  namespace: test_fla
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: postman-test 
