apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postman-test
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/postman-test/overlays/development
    repoURL: https://github.com/flacatus/test-postman1-gitops
    targetRevision: main
  destination:
    namespace: test_fla
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
